//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rztm.Helpers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rztm.Helpers.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodano do ulubionych.
        /// </summary>
        internal static string AddedToFavorites {
            get {
                return ResourceManager.GetString("AddedToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj do ulubionych.
        /// </summary>
        internal static string AddToFavorites {
            get {
                return ResourceManager.GetString("AddToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usunięto wszystkie przystanki.
        /// </summary>
        internal static string AllBusStopsHaveBeenRemoved {
            get {
                return ResourceManager.GetString("AllBusStopsHaveBeenRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wszystkie zapisane przystanki zostaną usunięte.
        /// </summary>
        internal static string AllSavedBusStopsWillBeDeleted {
            get {
                return ResourceManager.GetString("AllSavedBusStopsWillBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplikacja jest aktualna.
        /// </summary>
        internal static string ApplicationIsUpToDate {
            get {
                return ResourceManager.GetString("ApplicationIsUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rzeszowskie przystanki.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista przystanków.
        /// </summary>
        internal static string BusStopsListTitle {
            get {
                return ResourceManager.GetString("BusStopsListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień nazwę.
        /// </summary>
        internal static string ChangeName {
            get {
                return ResourceManager.GetString("ChangeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprawdź dostępność aktualizacji.
        /// </summary>
        internal static string CheckUpdatesAvailability {
            get {
                return ResourceManager.GetString("CheckUpdatesAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Połączono z internetem..
        /// </summary>
        internal static string ConnectedToInternet {
            get {
                return ResourceManager.GetString("ConnectedToInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd z połączeniem.
        /// </summary>
        internal static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wersja obecna.
        /// </summary>
        internal static string CurrentVersion {
            get {
                return ResourceManager.GetString("CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odrzuć.
        /// </summary>
        internal static string Discard {
            get {
                return ResourceManager.GetString("Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyświetl jako skrót.
        /// </summary>
        internal static string DisplayAsShortcut {
            get {
                return ResourceManager.GetString("DisplayAsShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobierz przystanki.
        /// </summary>
        internal static string DownloadBusStops {
            get {
                return ResourceManager.GetString("DownloadBusStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy chcesz pobrać aktualizację teraz?.
        /// </summary>
        internal static string DoYouWantToDownloadUpdateNow {
            get {
                return ResourceManager.GetString("DoYouWantToDownloadUpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy chcesz usunąć stary plik instalacyjny aplikacji (.apk)?.
        /// </summary>
        internal static string DoYouWantToRemoveOldApplicationInstallationFile {
            get {
                return ResourceManager.GetString("DoYouWantToRemoveOldApplicationInstallationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulubione.
        /// </summary>
        internal static string FavoritesTitle {
            get {
                return ResourceManager.GetString("FavoritesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtry.
        /// </summary>
        internal static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wprowadź nazwę przystanku....
        /// </summary>
        internal static string InsertBusStopName {
            get {
                return ResourceManager.GetString("InsertBusStopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak lokalnej bazy danych zawierającej przystanki autobusowe. Czy chcesz ją pobrać teraz?.
        /// </summary>
        internal static string LocalDatabaseContainingBusStopsMissing_DoYouWantDownloadItNow {
            get {
                return ResourceManager.GetString("LocalDatabaseContainingBusStopsMissing_DoYouWantDownloadItNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można określić lokalizacji.
        /// </summary>
        internal static string LocationCannotBeDetermined {
            get {
                return ResourceManager.GetString("LocationCannotBeDetermined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd lokalizacji.
        /// </summary>
        internal static string LocationError {
            get {
                return ResourceManager.GetString("LocationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapa.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak bazy danych przystanków.
        /// </summary>
        internal static string MissingBusStopDatabase {
            get {
                return ResourceManager.GetString("MissingBusStopDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak połączenia z internetem..
        /// </summary>
        internal static string MissingInternetConnection {
            get {
                return ResourceManager.GetString("MissingInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najbliższe.
        /// </summary>
        internal static string NearbyTitle {
            get {
                return ResourceManager.GetString("NearbyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak lokalizacji. Sprawdź GPS..
        /// </summary>
        internal static string NoLocationService_CheckGps {
            get {
                return ResourceManager.GetString("NoLocationService_CheckGps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak wyników.
        /// </summary>
        internal static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak zapisanych ulubionych.
        /// </summary>
        internal static string NoSavedFovorites {
            get {
                return ResourceManager.GetString("NoSavedFovorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otwórz w aplikacji mapy.
        /// </summary>
        internal static string OpenInMapApplication {
            get {
                return ResourceManager.GetString("OpenInMapApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń wszystkie przystanki.
        /// </summary>
        internal static string RemoveAllBusStops {
            get {
                return ResourceManager.GetString("RemoveAllBusStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usunięto z ulubionych.
        /// </summary>
        internal static string RemovedFromFavorites {
            get {
                return ResourceManager.GetString("RemovedFromFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strona domowa RTM.
        /// </summary>
        internal static string RtmHomepage {
            get {
                return ResourceManager.GetString("RtmHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szukaj w lini prostej.
        /// </summary>
        internal static string SearchInStraightLine {
            get {
                return ResourceManager.GetString("SearchInStraightLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz zakres.
        /// </summary>
        internal static string SelectRange {
            get {
                return ResourceManager.GetString("SelectRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tej operacji nie będzie można cofnąć. Kontynuować?.
        /// </summary>
        internal static string ThisOperationCannotBeUndone_Continue {
            get {
                return ResourceManager.GetString("ThisOperationCannotBeUndone_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spróbuj ponownie.
        /// </summary>
        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cofnij.
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualizacja.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostrzeżenie.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tak.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
